# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18fa90dafd9b5f8196dda4f5b4969eaeaed542c122c763975f390ec461f0b7754a246f511bf3a4066747f63885906fc868132f9c383d38a335d5e54b280fbc58

test:
  secret_key_base: 62f82171ba30479eaf643d464ef82aa4d302eb7301f76b300b401557ce0d242685432dbf71501b51e97da47559b36e10b9e6c809bdfb822f4d108171e2503160

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
